require 'rails_helper'

describe "the edit a book process" do
  it "takes you to an edit book page" do
    visit "/"
    click_on "Add an author"
    fill_in "First Name", :with=>"J.R."
    fill_in "Middle Initial", :with=>"R."
    fill_in "Last Name", :with=>"Tolkien"
    click_on "Create Author"
    click_on "Tolkien"
    click_on "Add a book"
    fill_in "Title", :with=> "The Fellowship of the Ring"
    fill_in "Summary", :with=>"Something about a ring, I think."
    click_on "Create Book"
    click_on "Fellowship"
    click_on "Add a chapter"
    fill_in "Number", :with =>"2"
    fill_in "Title", :with=>"The Council of Elrond"
    fill_in "Body", :with=>"Next day Frodo woke early..."
    click_on "Create Chapter"
    click_on "The Council"
    click_on "Edit"
    expect(page).to have_content "Edit Chapter"
  end

  it "edits a book" do
    visit "/"
    click_on "Add an author"
    fill_in "First Name", :with=>"J.R."
    fill_in "Middle Initial", :with=>"R."
    fill_in "Last Name", :with=>"Tolkien"
    click_on "Create Author"
    click_on "Tolkien"
    click_on "Add a book"
    fill_in "Title", :with=> "The Fellowship of the Ring"
    fill_in "Summary", :with=>"Something about a ring, I think."
    click_on "Create Book"
    click_on "Fellowship"
    click_on "Add a chapter"
    fill_in "Number", :with =>"2"
    fill_in "Title", :with=>"The Council of Elrond"
    fill_in "Body", :with=>"Next day Frodo woke early..."
    click_on "Create Chapter"
    click_on "The Council"
    click_on "Edit"
    fill_in "Number", :with =>"3"
    fill_in "Title", :with=>"The Ring Goes South"
    fill_in "Body", :with=>"Later that day the hobbits held a meeting of their own..."
    click_on "Update Chapter"
    expect(page).to have_content "edited"
  end

  it "gives an error when no title is entered" do
    visit "/"
    click_on "Add an author"
    fill_in "First Name", :with=>"J.R."
    fill_in "Middle Initial", :with=>"R."
    fill_in "Last Name", :with=>"Tolkien"
    click_on "Create Author"
    click_on "Tolkien"
    click_on "Add a book"
    fill_in "Title", :with=> "The Fellowship of the Ring"
    fill_in "Summary", :with=>"Something about a ring, I think."
    click_on "Create Book"
    click_on "Fellowship"
    click_on "Add a chapter"
    fill_in "Number", :with =>"2"
    fill_in "Title", :with=>"The Council of Elrond"
    fill_in "Body", :with=>"Next day Frodo woke early..."
    click_on "Create Chapter"
    click_on "The Council"
    click_on "Edit"
    fill_in "Number", :with =>"3"
    fill_in "Title", :with=>""
    fill_in "Body", :with=>"Later that day the hobbits held a meeting of their own..."
    click_on "Update Chapter"
    expect(page).to have_content 'Oops'
  end

  it "gives an error when no summary is entered" do
    visit "/"
    click_on "Add an author"
    fill_in "First Name", :with=>"J.R."
    fill_in "Middle Initial", :with=>"R."
    fill_in "Last Name", :with=>"Tolkien"
    click_on "Create Author"
    click_on "Tolkien"
    click_on "Add a book"
    fill_in "Title", :with=> "The Fellowship of the Ring"
    fill_in "Summary", :with=>"Something about a ring, I think."
    click_on "Create Book"
    click_on "Fellowship"
    click_on "Add a chapter"
    fill_in "Number", :with =>"2"
    fill_in "Title", :with=>"The Council of Elrond"
    fill_in "Body", :with=>"Next day Frodo woke early..."
    click_on "Create Chapter"
    click_on "The Council"
    click_on "Edit"
    fill_in "Number", :with =>"3"
    fill_in "Title", :with=>"The Ring Goes South"
    fill_in "Body", :with=>""
    click_on "Update Chapter"
    expect(page).to have_content 'Oops'
  end
end
