# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640c9b301bc79084d9ec4f51458f45c30211b4e95396c0b1620b44d725fa7d70c0ba0b260d874a85a03a1beeddd15f2852a6533818314ab9c7495aa849d47a9d

test:
  secret_key_base: 5838da34c783163addae1bcd08cac8a4599fccf0182d0a5278a78e6df520331c8ac98e6c37e0c8217f78f99e67456eeb43373900f1ce679d62f50ced3834650c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
